import "./globals.css";

/** @type {import('next').Metadata} */
export const metadata = {
  title: "Multiselect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
